// Kisrhombille lattice adjacency (see SPEC_002_KRB and geometry.py).
// Every fundamental triangle has exactly 3 edge-neighbors: 2 in the same
// hex (always sectors (s-1+12)%12 and (s+1)%12) and 1 cross-hex neighbor.
// The cross-hex table below is generated by
// scripts/generate_lattice_tables.py from the tested Python geometry
// module — do not hand-edit; regenerate and re-paste if the lattice ever
// changes.

export const NUM_SECTORS = 12;
export const SQRT3 = Math.sqrt(3.0);
export const SECTOR_ANGLE = Math.PI / 6.0;

// Generated by scripts/generate_lattice_tables.py — do not hand-edit.
// For sector i: the one edge-neighbor not in the same hex, as (dq, dr, targetSector).
// The other 2 neighbors are always sectors (i - 1 + 12) % 12 and (i + 1) % 12 in the same hex.
export const CROSS_HEX_NEIGHBOR = [
  { dq: 1, dr: 0, sector: 5 }, // sector 0
  { dq: 0, dr: 1, sector: 8 }, // sector 1
  { dq: 0, dr: 1, sector: 7 }, // sector 2
  { dq: -1, dr: 1, sector: 10 }, // sector 3
  { dq: -1, dr: 1, sector: 9 }, // sector 4
  { dq: -1, dr: 0, sector: 0 }, // sector 5
  { dq: -1, dr: 0, sector: 11 }, // sector 6
  { dq: 0, dr: -1, sector: 2 }, // sector 7
  { dq: 0, dr: -1, sector: 1 }, // sector 8
  { dq: 1, dr: -1, sector: 4 }, // sector 9
  { dq: 1, dr: -1, sector: 3 }, // sector 10
  { dq: 1, dr: 0, sector: 6 }, // sector 11
];

// Generated by scripts/generate_lattice_tables.py — do not hand-edit.
// For sector i: its 13 vertex-sharing (non-edge) neighbors, as (dq, dr, targetSector) triples
// (9 same-hex + 4 cross-hex from 2 other hexagons) — used by the optional 16-neighbor
// 'edge + vertex' extended rule mode. Combine with CROSS_HEX_NEIGHBOR + the 2 in-hex
// edge-neighbors for the full 16-neighbor set.
export const VERTEX_NEIGHBOR = [
  [{ dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 1, sector: 8 }, { dq: 0, dr: 1, sector: 9 }, { dq: 1, dr: 0, sector: 4 }, { dq: 1, dr: 0, sector: 6 }], // sector 0
  [{ dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }, { dq: 0, dr: 1, sector: 7 }, { dq: 0, dr: 1, sector: 9 }, { dq: 1, dr: 0, sector: 4 }, { dq: 1, dr: 0, sector: 5 }], // sector 1
  [{ dq: -1, dr: 1, sector: 10 }, { dq: -1, dr: 1, sector: 11 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }, { dq: 0, dr: 1, sector: 6 }, { dq: 0, dr: 1, sector: 8 }], // sector 2
  [{ dq: -1, dr: 1, sector: 9 }, { dq: -1, dr: 1, sector: 11 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }, { dq: 0, dr: 1, sector: 6 }, { dq: 0, dr: 1, sector: 7 }], // sector 3
  [{ dq: -1, dr: 0, sector: 0 }, { dq: -1, dr: 0, sector: 1 }, { dq: -1, dr: 1, sector: 8 }, { dq: -1, dr: 1, sector: 10 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }], // sector 4
  [{ dq: -1, dr: 0, sector: 1 }, { dq: -1, dr: 0, sector: 11 }, { dq: -1, dr: 1, sector: 8 }, { dq: -1, dr: 1, sector: 9 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }], // sector 5
  [{ dq: -1, dr: 0, sector: 0 }, { dq: -1, dr: 0, sector: 10 }, { dq: 0, dr: -1, sector: 2 }, { dq: 0, dr: -1, sector: 3 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }], // sector 6
  [{ dq: -1, dr: 0, sector: 10 }, { dq: -1, dr: 0, sector: 11 }, { dq: 0, dr: -1, sector: 1 }, { dq: 0, dr: -1, sector: 3 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 9 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }], // sector 7
  [{ dq: 0, dr: -1, sector: 0 }, { dq: 0, dr: -1, sector: 2 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 10 }, { dq: 0, dr: 0, sector: 11 }, { dq: 1, dr: -1, sector: 4 }, { dq: 1, dr: -1, sector: 5 }], // sector 8
  [{ dq: 0, dr: -1, sector: 0 }, { dq: 0, dr: -1, sector: 1 }, { dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 11 }, { dq: 1, dr: -1, sector: 3 }, { dq: 1, dr: -1, sector: 5 }], // sector 9
  [{ dq: 0, dr: 0, sector: 0 }, { dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 1, dr: -1, sector: 2 }, { dq: 1, dr: -1, sector: 4 }, { dq: 1, dr: 0, sector: 6 }, { dq: 1, dr: 0, sector: 7 }], // sector 10
  [{ dq: 0, dr: 0, sector: 1 }, { dq: 0, dr: 0, sector: 2 }, { dq: 0, dr: 0, sector: 3 }, { dq: 0, dr: 0, sector: 4 }, { dq: 0, dr: 0, sector: 5 }, { dq: 0, dr: 0, sector: 6 }, { dq: 0, dr: 0, sector: 7 }, { dq: 0, dr: 0, sector: 8 }, { dq: 0, dr: 0, sector: 9 }, { dq: 1, dr: -1, sector: 2 }, { dq: 1, dr: -1, sector: 3 }, { dq: 1, dr: 0, sector: 5 }, { dq: 1, dr: 0, sector: 7 }], // sector 11
];

/** Flattened `[dq, dr, sector]` ints for all 12 sectors, ready for a `uniform ivec3[12]`. */
export function crossHexNeighborUniformData() {
  const data = new Int32Array(12 * 3);
  for (let sector = 0; sector < NUM_SECTORS; sector++) {
    const entry = CROSS_HEX_NEIGHBOR[sector];
    data[sector * 3 + 0] = entry.dq;
    data[sector * 3 + 1] = entry.dr;
    data[sector * 3 + 2] = entry.sector;
  }
  return data;
}

export const NUM_VERTEX_NEIGHBORS_PER_SECTOR = 13;

/** Flattened `[dq, dr, sector]` ints for all 12 sectors x 13 vertex-neighbors, ready for a `uniform ivec3[12 * 13]`. */
export function vertexNeighborUniformData() {
  const data = new Int32Array(NUM_SECTORS * NUM_VERTEX_NEIGHBORS_PER_SECTOR * 3);
  for (let sector = 0; sector < NUM_SECTORS; sector++) {
    const entries = VERTEX_NEIGHBOR[sector];
    for (let i = 0; i < NUM_VERTEX_NEIGHBORS_PER_SECTOR; i++) {
      const base = (sector * NUM_VERTEX_NEIGHBORS_PER_SECTOR + i) * 3;
      data[base + 0] = entries[i].dq;
      data[base + 1] = entries[i].dr;
      data[base + 2] = entries[i].sector;
    }
  }
  return data;
}
