"""Regenerate the cross-hex neighbor lookup table used by the WebGL engine.

Every fundamental triangle's 2 in-hex neighbors are always sectors
`(sector - 1) mod 12` and `(sector + 1) mod 12` in the *same* hex (see
`geometry.py`'s adjacency discussion) — cheap enough to compute inline in
GLSL. Its 3rd (cross-hex) neighbor lives in a different hex, in one of the 6
standard axial hex directions, at some other sector — not a simple formula
of `sector`, so `web/js/lattice.js` embeds this table verbatim rather than
recomputing it in GLSL. This script derives it from the tested
`tiling_patterns.geometry.neighbors` (the single source of truth for the
lattice's adjacency) and prints it ready to paste into `lattice.js`, so the
embedded copy can be regenerated and diffed if the geometry ever changes.

Run: `python scripts/generate_lattice_tables.py`
"""

from __future__ import annotations

from tiling_patterns.geometry import CellAddress, HexCoord, neighbors, vertex_neighbors
from tiling_patterns.lattice import CROSS_HEX_NEIGHBOR as COMMITTED_TABLE
from tiling_patterns.lattice import VERTEX_NEIGHBOR as COMMITTED_VERTEX_TABLE

EDGE_LENGTH = 1.0
ORIGIN = HexCoord(0, 0)


def cross_hex_neighbor(sector: int) -> tuple[int, int, int]:
    """`(dq, dr, target_sector)` for the one neighbor of `sector` that is not
    in the same hex (identified as the neighbor whose hex differs from the
    origin's)."""
    address = CellAddress(ORIGIN, sector)
    candidates = [n for n in neighbors(address, EDGE_LENGTH) if n.hex != ORIGIN]
    if len(candidates) != 1:
        raise AssertionError(f"expected exactly 1 cross-hex neighbor for sector {sector}, got {candidates}")
    neighbor = candidates[0]
    return neighbor.hex.q - ORIGIN.q, neighbor.hex.r - ORIGIN.r, neighbor.sector


def main() -> None:
    entries = [cross_hex_neighbor(sector) for sector in range(12)]

    print("// Generated by scripts/generate_lattice_tables.py — do not hand-edit.")
    print("// For sector i: the one edge-neighbor not in the same hex, as (dq, dr, targetSector).")
    print("// The other 2 neighbors are always sectors (i - 1 + 12) % 12 and (i + 1) % 12 in the same hex.")
    print("export const CROSS_HEX_NEIGHBOR = [")
    for sector, (dq, dr, target_sector) in enumerate(entries):
        print(f"  {{ dq: {dq}, dr: {dr}, sector: {target_sector} }}, // sector {sector}")
    print("];")

    for sector, (dq, dr, target_sector) in enumerate(entries):
        back_address = CellAddress(HexCoord(ORIGIN.q + dq, ORIGIN.r + dr), target_sector)
        reciprocal = [n for n in neighbors(back_address, EDGE_LENGTH) if n == CellAddress(ORIGIN, sector)]
        if not reciprocal:
            raise AssertionError(f"cross-hex adjacency for sector {sector} is not reciprocal")
    print("\n// Reciprocity verified against tiling_patterns.geometry.neighbors for all 12 sectors.")

    if tuple(entries) != COMMITTED_TABLE:
        raise AssertionError(
            "src/tiling_patterns/lattice.py's CROSS_HEX_NEIGHBOR no longer matches geometry.neighbors "
            "— re-run this script and paste the freshly printed table into lattice.py and web/js/lattice.js."
        )
    print("Matches the committed tiling_patterns.lattice.CROSS_HEX_NEIGHBOR — no drift.")

    print()
    print_vertex_neighbor_table()


def print_vertex_neighbor_table() -> None:
    """The 13 vertex-sharing (non-edge) neighbors per sector — 9 same-hex plus
    4 cross-hex from 2 other hexagons — for the optional 16-neighbor extended
    ("edge + vertex") rule mode. See `geometry.vertex_neighbors`."""
    per_sector: list[list[tuple[int, int, int]]] = []
    for sector in range(12):
        address = CellAddress(ORIGIN, sector)
        entries = sorted(
            (n.hex.q - ORIGIN.q, n.hex.r - ORIGIN.r, n.sector) for n in vertex_neighbors(address, EDGE_LENGTH)
        )
        if len(entries) != 13:
            raise AssertionError(f"expected exactly 13 vertex-only neighbors for sector {sector}, got {len(entries)}")
        per_sector.append(entries)

    print("// Generated by scripts/generate_lattice_tables.py — do not hand-edit.")
    print("// For sector i: its 13 vertex-sharing (non-edge) neighbors, as (dq, dr, targetSector) triples")
    print("// (9 same-hex + 4 cross-hex from 2 other hexagons) — used by the optional 16-neighbor")
    print("// 'edge + vertex' extended rule mode. Combine with CROSS_HEX_NEIGHBOR + the 2 in-hex")
    print("// edge-neighbors for the full 16-neighbor set.")
    print("export const VERTEX_NEIGHBOR = [")
    for sector, entries in enumerate(per_sector):
        joined = ", ".join(f"{{ dq: {dq}, dr: {dr}, sector: {s} }}" for dq, dr, s in entries)
        print(f"  [{joined}], // sector {sector}")
    print("];")

    for sector, entries in enumerate(per_sector):
        for dq, dr, target_sector in entries:
            back_address = CellAddress(HexCoord(ORIGIN.q + dq, ORIGIN.r + dr), target_sector)
            reciprocal_keys = {(n.hex.q, n.hex.r, n.sector) for n in vertex_neighbors(back_address, EDGE_LENGTH)}
            if (ORIGIN.q, ORIGIN.r, sector) not in reciprocal_keys:
                raise AssertionError(f"vertex adjacency for sector {sector} -> ({dq},{dr},{target_sector}) is not reciprocal")
    print("\n// Reciprocity verified against tiling_patterns.geometry.vertex_neighbors for all 12 sectors.")

    committed_as_tuples = tuple(tuple(entries) for entries in per_sector)
    if committed_as_tuples != COMMITTED_VERTEX_TABLE:
        raise AssertionError(
            "src/tiling_patterns/lattice.py's VERTEX_NEIGHBOR no longer matches geometry.vertex_neighbors "
            "— re-run this script and paste the freshly printed table into lattice.py and web/js/lattice.js."
        )
    print("Matches the committed tiling_patterns.lattice.VERTEX_NEIGHBOR — no drift.")


if __name__ == "__main__":
    main()
