"""Regenerate the cross-hex neighbor lookup table used by the WebGL engine.

Every fundamental triangle's 2 in-hex neighbors are always sectors
`(sector - 1) mod 12` and `(sector + 1) mod 12` in the *same* hex (see
`geometry.py`'s adjacency discussion) — cheap enough to compute inline in
GLSL. Its 3rd (cross-hex) neighbor lives in a different hex, in one of the 6
standard axial hex directions, at some other sector — not a simple formula
of `sector`, so `web/js/lattice.js` embeds this table verbatim rather than
recomputing it in GLSL. This script derives it from the tested
`tiling_patterns.geometry.neighbors` (the single source of truth for the
lattice's adjacency) and prints it ready to paste into `lattice.js`, so the
embedded copy can be regenerated and diffed if the geometry ever changes.

Run: `python scripts/generate_lattice_tables.py`
"""

from __future__ import annotations

from tiling_patterns.geometry import CellAddress, HexCoord, neighbors
from tiling_patterns.lattice import CROSS_HEX_NEIGHBOR as COMMITTED_TABLE

EDGE_LENGTH = 1.0
ORIGIN = HexCoord(0, 0)


def cross_hex_neighbor(sector: int) -> tuple[int, int, int]:
    """`(dq, dr, target_sector)` for the one neighbor of `sector` that is not
    in the same hex (identified as the neighbor whose hex differs from the
    origin's)."""
    address = CellAddress(ORIGIN, sector)
    candidates = [n for n in neighbors(address, EDGE_LENGTH) if n.hex != ORIGIN]
    if len(candidates) != 1:
        raise AssertionError(f"expected exactly 1 cross-hex neighbor for sector {sector}, got {candidates}")
    neighbor = candidates[0]
    return neighbor.hex.q - ORIGIN.q, neighbor.hex.r - ORIGIN.r, neighbor.sector


def main() -> None:
    entries = [cross_hex_neighbor(sector) for sector in range(12)]

    print("// Generated by scripts/generate_lattice_tables.py — do not hand-edit.")
    print("// For sector i: the one edge-neighbor not in the same hex, as (dq, dr, targetSector).")
    print("// The other 2 neighbors are always sectors (i - 1 + 12) % 12 and (i + 1) % 12 in the same hex.")
    print("export const CROSS_HEX_NEIGHBOR = [")
    for sector, (dq, dr, target_sector) in enumerate(entries):
        print(f"  {{ dq: {dq}, dr: {dr}, sector: {target_sector} }}, // sector {sector}")
    print("];")

    for sector, (dq, dr, target_sector) in enumerate(entries):
        back_address = CellAddress(HexCoord(ORIGIN.q + dq, ORIGIN.r + dr), target_sector)
        reciprocal = [n for n in neighbors(back_address, EDGE_LENGTH) if n == CellAddress(ORIGIN, sector)]
        if not reciprocal:
            raise AssertionError(f"cross-hex adjacency for sector {sector} is not reciprocal")
    print("\n// Reciprocity verified against tiling_patterns.geometry.neighbors for all 12 sectors.")

    if tuple(entries) != COMMITTED_TABLE:
        raise AssertionError(
            "src/tiling_patterns/lattice.py's CROSS_HEX_NEIGHBOR no longer matches geometry.neighbors "
            "— re-run this script and paste the freshly printed table into lattice.py and web/js/lattice.js."
        )
    print("Matches the committed tiling_patterns.lattice.CROSS_HEX_NEIGHBOR — no drift.")


if __name__ == "__main__":
    main()
